### PR TITLE
Started standards chapter

### PR DESCRIPTION
**Pull request by sckott**
#29 

some notes:

- Just R and Python for now
- I'm not sure i'm happy with the list of items in R and Python. The last one in each just points to another chapter and says follow all of those. perhaps we have a human readable list in this chapter and then a checklist somewhere - perhaps we could adapt the usethis pkg to make a checklist automatically in an issue in the maitnainer's repo with the items to follow
- added section at bottom of chapter "Compliance with standards", I think we do need automation to make this work, though i'm not sure how yet. i'm asking around the web to see what works for folks

### CODE REVIEW

**Comment by sckott** [comment]
ping @tefirman - as chatted about in office hrs, can you:

- add a to do list for Docker to this chapter
- add a to do list for WDL to this chapter

Thanks!

**Comment by tefirman** [comment]
@sckott -- I added a first draft of some WDL and Docker standards as well as some details in the maintenance section. These might evolve over time as our WDL efforts mature, but I think this should be a good start. Thanks for the heads up on this!

**Comment by sckott** [comment]
Thanks @tefirman looks good to me

**Comment by sckott** [comment]
@seankross want to add anything for Nextflow and Research Compendia in the Standards chapter https://deploy-preview-30--monumental-cassata-2f9bb7.netlify.app/standards ? or leave blank for now?

**Comment by seankross** [comment]
@sckott I think we should leave both blank for now but I would love to collaborate with @monicagerber on the research compendia standards. @tefirman do you have nextflow expertise? (sorry for not knowing)

**Comment by sckott** [comment]
@seankross  Sounds good to leave em blank for now. 

can you review the PR now? perhaps we open another issue for a checklist

**Review by seankross — APPROVED** [review]
I think this is a great start and we should ship it! I have thoughts too about what we should add, but that's for another PR.

**Comment by sckott** [comment]
great, merging, thanks for looking

**Comment by monicagerber** [comment]
> @sckott I think we should leave both blank for now but I would love to collaborate with @monicagerber on the research compendia standards. @tefirman do you have nextflow expertise? (sorry for not knowing)

I'll draft up and open another PR.

**Comment by sckott** [comment]
thanks @monicagerber !

**Pull request merged**
